export const TEXTAREA_CARET_POSITION_UPDATE = 'TEXTAREA_CARET_POSITION_UPDATE';
export const START_TYPING_CITE = 'START_TYPING_CITE';
export const STOP_TYPING_CITE = 'STOP_TYPING_CITE';
export const CITE_SUGGESTION_SELECTED_INCREMENT = 'CITE_SUGGESTION_SELECTED_INCREMENT';
export const CITE_SUGGESTION_SELECTED_DECREMENT = 'CITE_SUGGESTION_SELECTED_DECREMENT';
export const UNAUTH_USER_ATTEMPT_CREATE_CONVERSATION = 'UNAUTH_USER_ATTEMPT_CREATE_CONVERSATION';
export const DISMISS_MODAL = 'DISMISS_MODAL';
export const CHOOSE_CITE = 'CHOOSE_CITE';